### ISSUE TITLE
Access course and event information from any device

### ISSUE THREAD

**Issue by JNicolin** [JNicolin/MS1-KiteAcademy#1]
### User story

**As a** user,  
**I need** easy access to information about courses and events, available across any device,  
**So that** I can select a training or event that suits my preferences.

---

### Acceptance criteria

- [x] Information on courses and events is published
- [x] A form to enroll in courses is available
- [x] Content is responsive and adapts to all screen sizes

---

### Tasks

- [x] Create a responsive layout of the website
- [x] Add a section with information about available courses and events
- [x] Add and optimize images that highlight the kitesurfing experience
- [x] Ensure that all content is accessible and usable on mobile, tablet, and desktop

---

### Related epic

`epic: Accessibility and Content`
