### ISSUE TITLE
Collect attendee details for planning and invoicing

### ISSUE THREAD

**Issue by JNicolin** [JNicolin/MS1-KiteAcademy#4]
### User Story

**As an** admin user,  
**I need** to know who has enrolled in courses or events, what their level of experience is and any specific requests,  
**So that** I can plan and prepare my sessions accordingly as well as send invoicing correctly.

---

### Acceptance Criteria

- [x] A form for reserving a seat in a training or event is published
- [x] There is visual feedback to the user after submitting the form
- [x] Name, phone number, and email fields are required

---

### Tasks

- [x] Add a page for making a reservation for a training class, surf camp, or event
- [x] Implement input fields for name, phone, email, experience level, and special requests
- [x] Make name, phone, and email mandatory
- [x] Create a pop-up or confirmation page/message as acknowledgement after submit
- [x] Test on desktop and mobile

---

### Related Epic

`epic: Communication and Conversion`
