### ISSUE TITLE
Collect newsletter sign-ups and contact permissions

### ISSUE THREAD

**Issue by JNicolin** [JNicolin/MS1-KiteAcademy#5]
### User story

**As a** copywriter with the academy,  
**I want** to know who has enrolled in the newsletter and accepted further contacts,  
**So that** I can segment and approach my audience with relevant information and thus attract further engagement and loyalty.

---

### Acceptance criteria

- [ ] There is a form for signing up to a newsletter or consenting to further contact
- [ ] A visual acknowledgement is shown after submitting the form

---

### Tasks

- [ ] Publish a form for accepting further contact via email or newsletter subscription
- [ ] Include required fields like name and email
- [ ] Create a pop-up or confirmation page/message to confirm the submission
- [ ] Ensure data is stored or sent appropriately for marketing segmentation

---

### Related epic

`epic: Communication and Conversion`
